### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by sajastu** [yuhaozhang/summarize-radiology-findings#1]
Just tying to train the model, but ending up with this error:

`Building Seq2Seq with Copy model ...
Using mlp attention for LSTM.
Finetune all embeddings.
[Update coverage loss weight to be 0]
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    loss = trainer.step(batch, eval=False) # update step
  File "private/summarize-radiology-findings/model/trainer.py", line 56, in step
    log_probs, attn, cov = self.model(src, tgt_in, bg)
  File "/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "private/summarize-radiology-findings/model/copy_model.py", line 197, in forward
    h_in, enc_hidden = self.encode(enc_inputs, src_lens, encoder=self.encoder)
  File "private/summarize-radiology-findings/model/copy_model.py", line 105, in encode
    packed_h_in, (hn, cn) = encoder(packed_inputs, (self.h0, self.c0))
  File "anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 192, in forward
    output, hidden = func(input, self.all_weights, hx, batch_sizes)
  File "anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 324, in forward
    return func(input, *fargs, **fkwargs)
  File "anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 288, in forward
    dropout_ts)
RuntimeError: CUDA error: out of memory
`

And this is the command I'm using: 
`python train.py --data_dir dataset/train --cuda 1 --batch_size 1`

It's worth mentioning that I tried the default --batch_size (which is set to 25) and 1. 

Thanks for spreading this code to the community

**Comment by yuhaozhang** [comment]
Hi @sajastu, the only issue I can see from the error message is that you've run out of your GPU memory. Do you know what GPU you are using and how large is the memory?

**Comment by sajastu** [comment]
Hi @yuhaozhang . Problem solved. Actually, I need relatively less batch size. I got two 1080Ti GPUs and 128GB of RAM. The main disk is fast, but small — only 350GB. Does the program has any argument pushing that it uses 2 GPUs? (multi-gpu)

Thanks,

**Comment by yuhaozhang** [comment]
Just out of curiosity: how did you solve it in the end?

It seems like a 1080Ti and 128GB of RAM should definitely be enough. For me all the training and testing in the paper are done with 12G GPU memory and some additional CPU memory. And sorry that the current program does not come with multi-gpu support.
